export const BASE_URL = process.env.NEXT_PUBLIC_BACKEND_API;
export const CLOUDINARY_CLOUD_NAME =
  process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME;
export const CLOUDINARY_UPLOAD_PRESET =
  process.env.NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET;
export const COMMENTS_PER_POST = 3;
export const POSTS_PER_PAGE = 5;
